Implement trapping of floating point exceptions while InstructionQueue is running.
Explanation:

For proper IEEE floating point arithmetic, things like dividing by zero,
illegal operations (e.g. sqrt(-1)), and overflow result in values like
NaN, -INF, and INF.  When debugging, it is difficult to determine where
such values originated, because they propagate through calculations.
For example, one may find that some code in Mesquite is failing because
a vertex has coordinates (NaN,NaN,NaN), but is quite difficult to
determine which code generated those values in the first place.

This change allows enabling of trapping for such errors.  When this
option is enabled, a calculation that results in such illegal values
will result in a SIGFPE.  This isn't a desirable behavior for an
application because the SIGFPE will typically result in a crash.  However,
for debugging, it will trap into the debugger at the point where the
calculation was made.  This makes finding the origin of such illegal
values MUCH easier.


Usage:

InstructionQueue now has the methods:
    void trap_floating_point_exception( bool enable );
    bool trap_floating_point_exception() const;
If this flag in InstructionQueue is set to true, trapping of floating
point exceptions will be enabled when the InstructionQueue begins.  The
original state will be restored when the call to InstructionQueue::run
returns.  NOTE:  This does not allow disabling of floating point
exception trapping.  The two options here are either unconditionally
enable trapping floating point exceptions or do whatever the application
has set up.  If the application has already enabled trapping, Mesquite
does not offer the option to disable it.

The default value for this flag is false unless either --enable-trap-fpe
or --enable-debug are specified to the configure script.  If anyone
objects to enabling this whenever --enable-debug is passed, let me know
and I'll change it.


Implementation Details:

The class MsqFPE provides a) static methods for a platform-independent
interface for this functionality and b) a utility class for
InstructionQueue to use for setting/restoring the FPE trapping flags.

There is no standard way to do this, but most platforms provide some
non-standard mechanism.  I have provided four alternate implementations.
The correct one to use is selected by the configure script.  The
implementations are:
  1) BSD-style fpsetmask - This one is the closest to
      a defacto standard on Unix-like OSes.  I think it will work
      for Sun, SGI, and the *BSDs.  Probably others also, but not Linux.
  2) GNU libc feenableexcept - This is unique to GNU libc, and
      works in Linux.
  3) An implementation specific to Microsoft VisualC++ and the
      x86 processor.  This is the only way I could find to do this
      on Windows.  The MS API is a very thin wrapper on around
      direct manipulation of the x86 floating point control register.
  4) An implementation that does nothing, for platforms that do
      not have any of the above.

I have only tested this on Linux.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -869,6 +869,9 @@ Optional Features:
   --disable-debug-output          Override default enable implied by --enable-debug
 
   --enable-function-timers        Enable function timers
+
+  --enable-trap-fpe               Enable trapping of floating point exceptions.
+                                  Default is no unless --enable-debug.
   --enable-tstt-mesh      Compile glue code for interfacing with TSTT
                           mesh implemenations.
   --disable-tstt-mesh     Disable TSTT mesh glue code (DEFAULT).
@@ -1488,6 +1491,7 @@ if test "${enable_debug+set}" = set; then
 else
   MSQ_DO_DEBUG="no"
 fi;
+
 # Check whether --enable-debug-output or --disable-debug-output was given.
 if test "${enable_debug_output+set}" = set; then
   enableval="$enable_debug_output"
@@ -1495,12 +1499,21 @@ if test "${enable_debug_output+set}" = set; then
 else
   MSQ_DEBUG_OUT=""
 fi;
+
 # Check whether --enable-function-timers or --disable-function-timers was given.
 if test "${enable_function_timers+set}" = set; then
   enableval="$enable_function_timers"
   MSQ_DO_TIMERS="$enableval"
 else
   MSQ_DO_TIMERS="no"
+fi;
+
+# Check whether --enable-trap-fpe or --disable-trap-fpe was given.
+if test "${enable_trap_fpe+set}" = set; then
+  enableval="$enable_trap_fpe"
+  MSQ_TRAP_FPE="$enableval"
+else
+  MSQ_TRAP_FPE=""
 fi;
 
 if test -z "$MSQ_DO_RELEASE"; then
@@ -1517,6 +1530,9 @@ if test "$MSQ_DO_DEBUG" != "no"; then
   if test -z "$MSQ_DEBUG_OUT"; then
     CXXFLAGS="$CXXFLAGS -DMSQ_ENABLE_DEBUG=1,2"
   fi
+  if test -z "$MSQ_TRAP_FPE"; then
+    MSQ_TRAP_FPE="yes"
+  fi
 fi
 
 if test -n "$MSQ_DEBUG_OUT"; then
@@ -1525,6 +1541,10 @@ if test -n "$MSQ_DEBUG_OUT"; then
   elif test "$MSQ_DEBUG_OUT" != "no"; then
     CXXFLAGS="$CXXFLAGS -DMSQ_ENABLE_DEBUG=$MSQ_DEBUG_OUT"
   fi
+fi
+
+if test "$MSQ_TRAP_FPE" = "yes"; then
+  CXXFLAGS="$CXXFLAGS -DMSQ_TRAP_FPE"
 fi
 
 if test "$MSQ_DO_TIMERS" = "yes"; then
@@ -4703,11 +4723,128 @@ fi
 done
 
 
+# Use C++ compiler because C allows undefined functions, so these
+# checks don't achive much if compiled as C.  Also, if C and C++
+# compilers are mis-matched, what works for one may not work for the
+# other and the C++ one is what is actually used for this in Mesquite.
+ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+echo "$as_me:$LINENO: checking for fpsetmask " >&5
+echo $ECHO_N "checking for fpsetmask ... $ECHO_C" >&6;
+
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <ieeefp.h>
+int
+main ()
+{
+fpsetmask(FP_X_INV|FP_X_OFL|FP_X_DZ);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  MSQ_FUNC_DEFS="${MSQ_FUNC_DEFS} -DHAVE_FPSETMASK"
+                 echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: checking for feenableexcept " >&5
+echo $ECHO_N "checking for feenableexcept ... $ECHO_C" >&6;
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#define _GNU_SOURCE
+                 #include <fenv.h>
+int
+main ()
+{
+feenableexcept(FE_DIVBYZERO|FE_INVALID|FE_OVERFLOW);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  MSQ_FUNC_DEFS="${MSQ_FUNC_DEFS} -DHAVE_FEENABLEEXCEPT"
+                 echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+
 
 #-----------------------------------------------------------------------------
 # Check C++ environment
 #-----------------------------------------------------------------------------
-
 
 echo "$as_me:$LINENO: checking for function-name preprocessor macro" >&5
 echo $ECHO_N "checking for function-name preprocessor macro... $ECHO_C" >&6
